// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260610074652_SeedInitialData_second")]
    partial class SeedInitialData_second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This stock is performing very well.",
                            CreatedOn = new DateTime(2024, 1, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            StockId = 1,
                            Title = "Great stock!"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Google is investing heavily in artificial intelligence.",
                            CreatedOn = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 2,
                            Title = "Strong AI Business"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Azure remains a major growth driver for Microsoft.",
                            CreatedOn = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 3,
                            Title = "Cloud Leader"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Amazon dominates online retail worldwide.",
                            CreatedOn = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 4,
                            Title = "E-commerce Giant"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Tesla stock remains highly volatile but promising.",
                            CreatedOn = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 5,
                            Title = "Volatile Stock"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Meta's advertising business is recovering strongly.",
                            CreatedOn = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 6,
                            Title = "Social Media Powerhouse"
                        });
                });

            modelBuilder.Entity("api.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LastDiv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Purchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Apple Inc.",
                            Industry = "Technology",
                            LastDiv = 0.92m,
                            MarketCap = 2800000L,
                            Purchase = 150.50m,
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Alphabet Inc.",
                            Industry = "Technology",
                            LastDiv = 0m,
                            MarketCap = 1800000L,
                            Purchase = 2750.30m,
                            Symbol = "GOOGL"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Microsoft Corporation",
                            Industry = "Technology",
                            LastDiv = 3.00m,
                            MarketCap = 3100000L,
                            Purchase = 420.75m,
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Amazon.com Inc.",
                            Industry = "E-Commerce",
                            LastDiv = 0m,
                            MarketCap = 1900000L,
                            Purchase = 185.40m,
                            Symbol = "AMZN"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Tesla Inc.",
                            Industry = "Automotive",
                            LastDiv = 0m,
                            MarketCap = 850000L,
                            Purchase = 240.25m,
                            Symbol = "TSLA"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Meta Platforms Inc.",
                            Industry = "Technology",
                            LastDiv = 2.00m,
                            MarketCap = 1300000L,
                            Purchase = 510.60m,
                            Symbol = "META"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "NVIDIA Corporation",
                            Industry = "Semiconductors",
                            LastDiv = 0.16m,
                            MarketCap = 3200000L,
                            Purchase = 890.45m,
                            Symbol = "NVDA"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "JPMorgan Chase & Co.",
                            Industry = "Banking",
                            LastDiv = 4.20m,
                            MarketCap = 600000L,
                            Purchase = 210.80m,
                            Symbol = "JPM"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Visa Inc.",
                            Industry = "Financial Services",
                            LastDiv = 2.08m,
                            MarketCap = 550000L,
                            Purchase = 290.15m,
                            Symbol = "V"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "The Coca-Cola Company",
                            Industry = "Beverages",
                            LastDiv = 1.94m,
                            MarketCap = 270000L,
                            Purchase = 62.90m,
                            Symbol = "KO"
                        });
                });

            modelBuilder.Entity("api.Models.Comment", b =>
                {
                    b.HasOne("api.Models.Stock", "Stock")
                        .WithMany("Comments")
                        .HasForeignKey("StockId");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("api.Models.Stock", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
